apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-applications
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: applications

  source:
    repoURL: https://github.com/GITHUB_USERNAME/gitops-platform-lab.git
    targetRevision: main
    path: applications/demo-app

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

---
# Note: This will be expanded in later phases to support:
# - Multiple applications
# - Environment-specific overlays (dev, staging, production)
# - Progressive delivery with Argo Rollouts
