apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Platform infrastructure services

  # Source repositories
  sourceRepos:
    - '*'

  # Destination clusters and namespaces
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc

  # Cluster resource allow list
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  # Namespace resource allow list
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'

  # Orphaned resources monitoring
  orphanedResources:
    warn: true
