apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # Repository credentials (update with your GitHub repo)
  repositories: |
    - url: https://github.com/GITHUB_USERNAME/gitops-platform-lab.git
      type: git

  # Resource customizations for Argo Rollouts
  resource.customizations: |
    argoproj.io/Rollout:
      health.lua: |
        hs = {}
        if obj.status ~= nil then
          if obj.status.phase == "Degraded" then
            hs.status = "Degraded"
            hs.message = obj.status.message
            return hs
          end
          if obj.status.phase == "Progressing" then
            hs.status = "Progressing"
            hs.message = obj.status.message
            return hs
          end
        end
        hs.status = "Healthy"
        return hs

  # UI customizations
  ui.bannercontent: "GitOps Platform Lab - Demo Environment"
  ui.bannerurl: "https://github.com/GITHUB_USERNAME/gitops-platform-lab"

  # Application settings
  application.instanceLabelKey: argocd.argoproj.io/instance

  # Timeout settings
  timeout.reconciliation: 180s
