# ArgoCD ConfigMap patch for Argo Rollouts resource customization
# This enables ArgoCD to understand Rollout health status
#
# Apply with:
# kubectl patch configmap argocd-cm -n argocd --patch-file argocd-cm-rollouts.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  # Resource customizations for Argo Rollouts
  resource.customizations.health.argoproj.io_Rollout: |
    hs = {}
    if obj.status ~= nil then
      if obj.status.phase ~= nil then
        if obj.status.phase == "Degraded" then
          hs.status = "Degraded"
          hs.message = obj.status.message
          return hs
        end
        if obj.status.phase == "Progressing" then
          hs.status = "Progressing"
          hs.message = obj.status.message
          return hs
        end
      end
      if obj.status.currentPodHash == obj.status.stableRS then
        hs.status = "Healthy"
        hs.message = "Rollout is healthy and stable"
        return hs
      end
    end
    hs.status = "Progressing"
    hs.message = "Waiting for rollout to finish"
    return hs
